// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD154t7zaRWzGMHxGcokjgfNr8gbGyG9Gw',
    appId: '1:883759176069:web:4c1e70f91f82f1466e0cec',
    messagingSenderId: '883759176069',
    projectId: 'task-manager-a28d6',
    authDomain: 'task-manager-a28d6.firebaseapp.com',
    storageBucket: 'task-manager-a28d6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDSUXheGBUJWLq1TWYA3HEJTkAJOzfw8U',
    appId: '1:883759176069:android:17e0c6ebc8397cce6e0cec',
    messagingSenderId: '883759176069',
    projectId: 'task-manager-a28d6',
    storageBucket: 'task-manager-a28d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLV1038Emu8TLJesUXxgEbddZrOtwjHGM',
    appId: '1:883759176069:ios:744358a34874d0206e0cec',
    messagingSenderId: '883759176069',
    projectId: 'task-manager-a28d6',
    storageBucket: 'task-manager-a28d6.firebasestorage.app',
    iosBundleId: 'com.example.taskManagerFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLV1038Emu8TLJesUXxgEbddZrOtwjHGM',
    appId: '1:883759176069:ios:744358a34874d0206e0cec',
    messagingSenderId: '883759176069',
    projectId: 'task-manager-a28d6',
    storageBucket: 'task-manager-a28d6.firebasestorage.app',
    iosBundleId: 'com.example.taskManagerFirebase',
  );
}
